config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  namespace :admin do
    get "" => "homes#top"
    resources :posts, only: [:show, :destroy] do
      delete "post_comments/:id" => "posts#comment_destroy", as: "comment_destroy"
    end
    resources :large_categories, except: [:new, :show], shallow: true do
      resources :item_categories, except: [:new, :show]
    end
    resources :users, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root "homes#top"
    get "about" => "homes#about"

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :post_favorites, only: [:create, :destroy]
    end

    resources :categories, only: [:index]

    resources :users, only: [:show, :edit, :update] do
      get "my_posts" => "users#my_posts"
      get "my_favorites" => "users#my_favorites"
      get "confirm" => "users#confirm"
      patch "deleted" => "users#deleted"
    end

    get "search" => "searches#search"
    get "category/:id" => "searches#large_category_search", as: "large_category_search"
    get "category/:large_category_id/item_category/:id" => "searches#item_category_search", as: "item_category_search"
    # category.jsのリクエストを送信するためのURL
    get "get_item_category" => "categories#get_item_category"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :large_category
  has_many :posts, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/item_categories_controller.rb
class Admin::ItemCategoriesController < ApplicationController
  before_action :admin_sign_in?

  def index
    @large_category = LargeCategory.find(params[:large_category_id])
    # 空白値は表示しない
    @item_categories = @large_category.item_categories.where.not(large_category_id: nil)
    @item_category = @item_categories.new
  end

  def create
    @large_category = LargeCategory.find(params[:large_category_id])
    @item_categories = @large_category.item_categories.where.not(large_category_id: nil)
    @item_category = @item_categories.new(item_category_params)
    if @item_category.save
      flash[:notice] = "登録が完了しました。"
      redirect_to admin_large_category_item_categories_path(@large_category)
    else
      flash[:alert] = "カテゴリ(小分類)名を入力してください。"
      render :index
    end
  end

  def edit
    @item_category = ItemCategory.find(params[:id])
  end

  def update
    @item_category = ItemCategory.find(params[:id])
    if @item_category.update(item_category_params)
      flash[:notice] = "更新が完了しました。"
      redirect_to admin_large_category_item_categories_path(@item_category.large_category)
    else
      flash[:alert] = "カテゴリ(小分類)名を入力してください。"
      render :edit
    end
  end

  def destroy
    item_category = ItemCategory.find(params[:id])
    item_category.destroy
    redirect_to admin_large_category_item_categories_path(item_category.large_category)
  end

  private
    def item_category_params
      params.require(:item_category).permit(:name)
    end

    def admin_sign_in?
      unless admin_signed_in?
        redirect_to new_admin_session_path
        flash[:alert] = "サイトを使用するにはログインをしてください。"
      end
    end
end

app/helpers/admin/item_categories_helper.rb
module Admin::ItemCategoriesHelper
end

app/views/admin/item_categories/edit.html.erb
<div class="container mb-5">
  <div class="field_with_errors">
  <h5>カテゴリ(小分類)編集</h5>
    <%= form_with model: @item_category, url: admin_item_category_path(@item_category), method: :patch do |f| %>
      <b><%= f.label :name, "カテゴリ名" %></b>
      <%= f.text_field :name, placeholder: "カテゴリ名", :size=>"40" %>
      <%= f.submit "変更を保存", class: "btn btn-outline-success" %>
    <% end %>
  </div>
  <button class="btn btn-outline-primary mt-5" onclick="history.back(-1)">戻る</button>
</div>

app/views/admin/item_categories/index.html.erb
<div class="container">
  <div class="field_with_errors">
    <h1><%= @large_category.name %></h1>
    <%= form_with model: @item_category, url: admin_large_category_item_categories_path(@large_category) do |f| %>
      <b><%= f.label :name, "カテゴリ名" %></b>
      <%= f.text_field :name, placeholder: "カテゴリ名(小分類)", :size=>"40" %>
      <%= f.submit "新規登録", class: "btn btn-outline-warning" %>
    <% end %>
  </div>

  <h4>カテゴリ一覧</h4>
  <div class="row">
    <% @item_categories.each do |item_category| %>
      <div class="col-6">
        <h6>
          <ul class="category">
            <li>
              <%= item_category.name %>
              <%= link_to "編集する", edit_admin_item_category_path(item_category.id), class: "btn btn-outline-success" %>
              <%= link_to "削除する", admin_item_category_path(item_category), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-outline-danger" %>
            </li>
          </ul>
        </h6>
      </div>
    <% end %>
  </div>
  <%= link_to "戻る", admin_large_categories_path, class: "btn btn-outline-primary mb-3" %>
</div>