config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  namespace :admin do
    get "" => "homes#top"
    resources :posts, only: [:show, :destroy] do
      delete "post_comments/:id" => "posts#comment_destroy", as: "comment_destroy"
    end
    resources :large_categories, except: [:new, :show], shallow: true do
      resources :item_categories, except: [:new, :show]
    end
    resources :users, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root "homes#top"
    get "about" => "homes#about"

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :post_favorites, only: [:create, :destroy]
    end

    resources :categories, only: [:index]

    resources :users, only: [:show, :edit, :update] do
      get "my_posts" => "users#my_posts"
      get "my_favorites" => "users#my_favorites"
      get "confirm" => "users#confirm"
      patch "deleted" => "users#deleted"
    end

    get "search" => "searches#search"
    get "category/:id" => "searches#large_category_search", as: "large_category_search"
    get "category/:large_category_id/item_category/:id" => "searches#item_category_search", as: "item_category_search"
    # category.jsのリクエストを送信するためのURL
    get "get_item_category" => "categories#get_item_category"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :admin_sign_in?

  def top
    # 投稿一覧画面の並び替え表示
    if params[:latest]
      @posts = Post.privacy.latest.page(params[:page]).per(24)
    elsif params[:old]
      @posts = Post.privacy.old.page(params[:page]).per(24)
    elsif params[:post_favorite_count]
      posts = Post.privacy.post_favorite_count
      @posts = Kaminari.paginate_array(posts).page(params[:page]).per(24) # 配列に対してページャを作成
    elsif params[:score_count]
      @posts = Post.privacy.score_count.page(params[:page]).per(24)
    else
      @posts = Post.privacy.page(params[:page]).per(24).order("created_at DESC")
    end
    @total_posts = Post.privacy.count
  end

  private
    def admin_sign_in?
      unless admin_signed_in?
        redirect_to new_admin_session_path
        flash[:alert] = "サイトを使用するにはログインをしてください。"
      end
    end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <h5>会員の投稿一覧(全<%= @total_posts %>件)</h5>
  <%= link_to "新しい順", admin_path(latest: "true") %>
  |<%= link_to "古い順", admin_path(old: "true") %>
  |<%= link_to "いいねの多い順", admin_path(post_favorite_count: "true") %>
  |<%= link_to "スコアの低い順", admin_path(score_count: "true") %>
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-12 col-md-3">
        <%= link_to admin_post_path(post) do %>
          <%= image_tag post.get_item_image, size: "200x200" %>
        <% end %>
        <div class="text-decoration-none text-danger"><i class="fas fa-heart"></i><%= post.post_favorites.count %></div>
        <div style="word-wrap:break-word; width:200px;">
          <b><%= post.item_name %></b></br>
        </div>
        <div class="small">コメント件数：<%= post.post_comments.count %></div>
        <!--スコアの値に応じて色分け-->
        <% if post.score >= 0 %>
          <div class="text-info font-weight-bold">ポジティブスコア[<%= post.score %>]</div>
        <% else %>
          <div class="text-danger font-weight-bold">ネガティブスコア[<%= post.score %>]</div>
        <% end %>
        <div id="star<%= post.id %>">
          <script>
            $('#star<%= post.id %>').empty();
            $('#star<%= post.id %>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              starHalf  : '<%= asset_path('star-half.png') %>',
              half      : true,
              readOnly  : true,
              score     : '<%= post.rate %>',
            });
          </script>
        </div>
        <div style="word-wrap:break-word; width:200px;">
          <%= image_tag post.user.get_profile_image, class: "rounded-circle", size: "50x50" %>
        </div>
        <div><%= link_to post.user.nickname, admin_user_path(post.user), class: "text-dark" %>さん</div>
      </div>
    <% end %>
  </div>
  <div class="pagination d-flex justify-content-center">
    <%= paginate @posts %>
  </div>
</div>