config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  namespace :admin do
    get "" => "homes#top"
    resources :posts, only: [:show, :destroy] do
      delete "post_comments/:id" => "posts#comment_destroy", as: "comment_destroy"
    end
    resources :large_categories, except: [:new, :show], shallow: true do
      resources :item_categories, except: [:new, :show]
    end
    resources :users, only: [:index, :show, :edit, :update]
  end

  scope module: :public do
    root "homes#top"
    get "about" => "homes#about"

    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :post_favorites, only: [:create, :destroy]
    end

    resources :categories, only: [:index]

    resources :users, only: [:show, :edit, :update] do
      get "my_posts" => "users#my_posts"
      get "my_favorites" => "users#my_favorites"
      get "confirm" => "users#confirm"
      patch "deleted" => "users#deleted"
    end

    get "search" => "searches#search"
    get "category/:id" => "searches#large_category_search", as: "large_category_search"
    get "category/:large_category_id/item_category/:id" => "searches#item_category_search", as: "item_category_search"
    # category.jsのリクエストを送信するためのURL
    get "get_item_category" => "categories#get_item_category"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer style="margin-top:50px;">
<% if admin_signed_in? %>
  <div class="container-fluid fixed-bottom" style="background-color:#00c7ce;">
<% else %>
  <div class="container-fluid fixed-bottom" style="background-color:#ff9933;">
<% end %>
    <div class="row">
      <div class="mx-auto">
        <p><small>&copy; YumMemory</small></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
<!--会員ログインまたは管理者ログインによってヘッダーを色分け-->
<% if admin_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#00c7ce;">
    <a class="navbar-brand ml-5" href="/admin"><%= image_tag 'logo.png', size: "150x100" %></a>
<% else %>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#ff9933;">
    <a class="navbar-brand ml-5" href="/"><%= image_tag 'logo.png', size: "150x100" %></a>
<% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <!--ユーザーがログインしている時 -->
          <li>
            <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-address-card"></i>マイページ
            <% end %>
          </li>
          <li>
            <%= link_to posts_path, class: "nav-link text-light" do %>
              <i class="fas fa-marker"></i>みんなの投稿一覧
            <% end %>
          </li>
          <li>
            <%= link_to user_my_favorites_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-heart"></i>お気に入り
            <% end %>
          </li>
          <li>
            <%= link_to categories_path, class: "nav-link text-light" do %>
              <i class="fas fa-search"></i>カテゴリで検索する
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>
        <% elsif admin_signed_in? %>

        <!-- 管理者がログインしている時 -->
          <li>
            <%= link_to admin_users_path, class: "nav-link text-light" do %>
              <i class="fas fa-users"></i>会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_path, class: "nav-link text-light" do %>
              <i class="fas fa-pencil-alt"></i>レビュー履歴一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_large_categories_path, class: "nav-link text-light" do %>
              <i class="fas fa-folder"></i>カテゴリ一覧・追加
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>
        <% else %>
        <!-- ログインしていない時 -->
          <li>
            <%= link_to about_path, class: "nav-link text-light" do %>
              <i class="fas fa-shopping-basket"></i>サイト概要
            <% end %>
          </li>
          <li>
            <%= link_to users_guest_sign_in_path, method: :post, class: "nav-link text-light" do %>
              <i class="fas fa-user"></i>ゲストログイン(閲覧用)
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i>新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt text-light"></i>ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render "public/searches/search" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YumMemory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <p class="text-success mt-3"><b><%= flash[:notice] %></b></p>
      <p class="text-danger mt-3"><b><%= flash[:alert] %></b></p>
    </div>
    <%= yield %>
    <%= render "layouts/footer"%>
  </body>
</html>